### ISSUE TITLE
插件没有任何反应, 不起作用

### ISSUE THREAD

**Issue by izilongwan** [yaegar/vscode-mybatis#1]
![image](https://user-images.githubusercontent.com/48234072/205019853-8dd710da-2a6a-4bf4-b7cd-1f5a4646be74.png)
![image](https://user-images.githubusercontent.com/48234072/205019934-028be053-062d-48bf-b974-92b07a397d45.png)
![image](https://user-images.githubusercontent.com/48234072/205020012-8051f959-9bb7-4e86-97f4-f4367f39f418.png)
![image](https://user-images.githubusercontent.com/48234072/205020063-287b6e73-c334-4b2f-aa65-1c6341c1c1d9.png)
![image](https://user-images.githubusercontent.com/48234072/205020194-53f178cb-71d8-45fd-a4d0-bbf11e40b794.png)

**Comment by Carson-yy** [comment]
该问题解决没？目前来看是插件没有加载，该插件依赖于Redhat Java插件，确认是否安装？

**Comment by izilongwan** [comment]
更新版本有有了发自我的手机

**Comment by Carson-yy** [comment]
> 更新版本有有了发自我的手机

正常了是吧？

**Comment by izilongwan** [comment]
> > 更新版本有有了发自我的手机
> 
> 正常了是吧？

是的

**Comment by Carson-yy** [comment]
已解决
