### ISSUE TITLE
打开单文件Java时报错“找不到有效的workspace”

### ISSUE THREAD

**Issue by Faputa** [yaegar/vscode-mybatis#12]
我认为打开单文件Java的时候插件不应该被激活

**Comment by Carson-yy** [comment]
> 我认为打开单文件Java的时候插件不应该被激活

目前激活action是设定vscode识别语言是Java语言或包含了maven、Gradle等一系列相关文件作为激活事件，即便插件处理，实际上插件还是激活的，只是屏蔽了这种错误！

**Comment by Carson-yy** [comment]
fix 2023.7.3
