### ISSUE TITLE
不能使用快捷键f12从xml文件跳转到java文件中对应方法的声明处

### ISSUE THREAD

**Issue by zhanghel1ng** [yaegar/vscode-mybatis#17]
不能使用快捷键f12从xml mapper 跳转到 java mapper
vscode v1.85.0
mybatisx v2023.11.2901
mybatisx 除了关掉装饰忍者鸟其余均为默认设置
项目为spring boot

**Comment by Carson-yy** [comment]
已在2023.12.19/2023.12.20（preview）中修复

**Comment by zhanghel1ng** [comment]
谢谢
