### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by ShouHuJiYi** [yaegar/vscode-mybatis#3]
![image](https://user-images.githubusercontent.com/48313450/215438629-38f1a082-7ff5-4421-928a-668c17afc8f7.png)

**Comment by ShouHuJiYi** [comment]
手动安装也是失败

**Comment by yaegar** [comment]
提供下报错截图

**Comment by Carson-yy** [comment]
> 手动安装也是失败

需要点击日志 提供具体报错内容

**Comment by ShouHuJiYi** [comment]
当天应该是本地电脑环境有问题，后续尝试，安装成功了，感谢！
