### ISSUE TITLE
Go to mapper支持快捷键

### ISSUE THREAD

**Issue by zwed2000** [yaegar/vscode-mybatis#4]
通过F12快捷键，从java代码跳转到mapper.xml文件中
使用vim则是gd跳转到xml文件中

**Comment by Faputa** [comment]
vscode中F12跳转到定义，CTRL+F12跳转到实现，所以应该用CTRL+F12跳转到xml文件中

**Comment by Carson-yy** [comment]
> vscode中F12跳转到定义，CTRL+F12跳转到实现，所以应该用CTRL+F12跳转到xml文件中

后续会以贴近vscode自带快捷键方式来完成该功能，当然也支持自定义快捷键

**Comment by Carson-yy** [comment]
2023.4.81006011 版本增加在Java Mapper跳转到实现（方法名上），Xml Mapper跳转到定义功能（id属性值上），快捷键使用vscode定义的跳转到实现和跳转到定义即可。
