### ISSUE TITLE
没有起作用

### ISSUE THREAD

**Issue by izilongwan** [yaegar/vscode-mybatis#5]
Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/48234072/223917703-90459060-5620-46dd-afe7-9f6239e5c34c.png)

Extension version: 2023.2.20084401
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.48GB free)|
|Process Argv|-n --enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id f24fe983-78b2-424b-b832-a858c79abae1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
pythonms35:30680984

```

</details>

**Comment by izilongwan** [comment]
> Type: Bug
> 
> ![image](https://user-images.githubusercontent.com/48234072/223917703-90459060-5620-46dd-afe7-9f6239e5c34c.png)
> 
> Extension version: 2023.2.20084401 VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z) OS version: Windows_NT x64 10.0.19043 Modes: Sandboxed: Yes
> 
> System Info
> A/B Experiments

好像必须先创建mapper.xml 才可以，不然没反应

**Comment by Carson-yy** [comment]
> > Type: Bug
> > ![image](https://user-images.githubusercontent.com/48234072/223917703-90459060-5620-46dd-afe7-9f6239e5c34c.png)
> > Extension version: 2023.2.20084401 VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z) OS version: Windows_NT x64 10.0.19043 Modes: Sandboxed: Yes
> > System Info
> > A/B Experiments
> 
> 好像必须先创建mapper.xml 才可以，不然没反应


是这样的，如果单纯的判断Java定义的Mapper文件，会导出大工程的时候加载异常慢。

但是每个工程的xml Mapper数量远远小于Java文件，这块做了反向查找，从xml Mapper找对应的Java文件

考虑后期会根据springboot项目配置文件解析以及加入一些配置（兼容J2SE）来完成这个功能

**Comment by Carson-yy** [comment]
目前针对其他IDE产品调研，暂无法完美识别Java文件是否为Mapper，先关闭了！
