### ISSUE TITLE
mapper.xml里面到sql格式化功能会有么？

### ISSUE THREAD

**Issue by hks2002** [yaegar/vscode-mybatis#6]

**Comment by Carson-yy** [comment]
会考虑加入这个功能，不过这个插件是我闲于之作，适配周期较长！耐心等待

**Comment by Carson-yy** [comment]
需求特性记录，周期安排，先关了

**Comment by bluef1ash** [comment]
一年半了，强烈希望加入 XML 的格式化功能，要不然让其他插件格式化后简直不可读

**Comment by Carson-yy** [comment]
> 一年半了，强烈希望加入 XML 的格式化功能，要不然让其他插件格式化后简直不可读

哈哈，上班太忙了，我尽力加快速度

**Comment by phakeandy** [comment]
这个格式化有解决办法吗？我尝试把 redhat xml 拓展的 format 选项：xml.format.joinContentLines 关掉依然会格式化<select> tag 包裹起来的sql，怀疑原因是 xml 拓展格式化会被 mybatis dtd 影响。最终换了一个 formatter 部分解决了：https://github.com/DotJoshJohnson/vscode-xml。不过这个拓展不会像 idea 那样格式化 sql，而是保留原样。
