### ISSUE TITLE
有些mapper需要手动修改保存后才能正常识别

### ISSUE THREAD

**Issue by JerryGreenLuan** [yaegar/vscode-mybatis#7]
最近使用插件看springboot项目，发现有些mapper class识别不到对应的xml。但是，我如果手动修改一下xml，哪怕任何内容都不改，只是删除一个字母再写上，然后手动保存就又能识别了。这个问题虽然不大，但是很影响看代码的效率。麻烦作者大大修复此问题，感谢！
![微信截图_20230424094526](https://user-images.githubusercontent.com/13307949/233882320-0e264ff9-63c3-46ed-9b40-dd376f6d7845.png)
![微信截图_20230424094755](https://user-images.githubusercontent.com/13307949/233882345-03bfa265-0f15-4fa0-8b99-8f233e14d976.png)
![动画](https://user-images.githubusercontent.com/13307949/233882353-d24d4ce6-8512-4a28-a034-a4fab86e933b.gif)
![1682301384750](https://user-images.githubusercontent.com/13307949/233882361-3a1431e0-f1ed-4755-a9c1-57bf3d250fa2.png)

**Comment by Carson-yy** [comment]
1. 确认下该文件是不是导入第三方Jar内的？

**Comment by Carson-yy** [comment]
麻烦确认下以下问题：
1. xml文件和jar文件是否都是当前工作目录下的文件?（非jar引入）
2. 是否所有xml文件均不识别?
3. 能否描述下项目的工作目录树或者截图给我（尽量标注下目标文件）

**Comment by JerryGreenLuan** [comment]
> 麻烦确认下以下问题：
> 
> 1. XML文件和jar文件是否都是当前工作目录下的文件？（非jar引入）
是的，都是当前工程的文件。
> 2. 是否所有XML文件均不识别？
不是的，只是有些xml文件不识别。
> 3. 能否描述下项目的工作目录树或者截图给我（尽量标注下目标文件）
当前工程是spring boot+mybatis plus，有些查询mybatis plus不满足我的需求，自己手写了一些xml，工程目录如下：
![微信截图_20230425091117](https://user-images.githubusercontent.com/13307949/234150913-81ea5182-fcab-4e05-ac77-5ef6a362f75e.png)
![微信截图_20230425091425](https://user-images.githubusercontent.com/13307949/234150917-e8247942-1134-4473-a260-1bb4854b595e.png)
这个问题似乎是偶现的，我在家里的电脑上看项目，确实是都能识别出来了。
我的本机环境是wsl+docker。

**Comment by Carson-yy** [comment]
> > 麻烦确认下以下问题：
> > 
> > 1. XML文件和jar文件是否都是当前工作目录下的文件？（非jar引入）
> >    是的，都是当前工程的文件。
> > 2. 是否所有XML文件均不识别？
> >    不是的，只是有些xml文件不识别。
> > 3. 能否描述下项目的工作目录树或者截图给我（尽量标注下目标文件）
> >    当前工程是spring boot+mybatis plus，有些查询mybatis plus不满足我的需求，自己手写了一些xml，工程目录如下：
> >    ![微信截图_20230425091117](https://user-images.githubusercontent.com/13307949/234150913-81ea5182-fcab-4e05-ac77-5ef6a362f75e.png)
> >    ![微信截图_20230425091425](https://user-images.githubusercontent.com/13307949/234150917-e8247942-1134-4473-a260-1bb4854b595e.png)
> >    这个问题似乎是偶现的，我在家里的电脑上看项目，确实是都能识别出来了。
> >    我的本机环境是wsl+docker。

你好，麻烦切换到2023.5.3 预发布版本上，对上面的问题进行复现，同时麻烦点击下状态bar上面的MybatisX字样，把弹出的日志上传一份给我

**Comment by Carson-yy** [comment]
时间很久没有回复，先关闭了！
