### ISSUE TITLE
无法自动生成Mapper对应的xml文件

### ISSUE THREAD

**Issue by RoureUnder** [yaegar/vscode-mybatis#8]
![image](https://user-images.githubusercontent.com/80234931/234470142-d7f5ca15-74ad-4f78-aabf-631c73076493.png)
工作树如上图，dao层中是mapper文件，mapper文件夹是xml文件。
在dao层里标记了mapper文件，无法在mapper文件夹中自动生成对应的xml文件(没有任何提示)，
![image](https://user-images.githubusercontent.com/80234931/234469973-df41d7a6-741c-4abf-876a-7bf4afc01f8d.png)
但是在mapper文件夹里面自己手动创建好一个完整的xml文件后，在dao里面写方法会在创建的xml里面自动生成对应节点
![image](https://user-images.githubusercontent.com/80234931/234470013-ec1df6c3-c6e7-4e88-85be-44079ee9679d.png)
![image](https://user-images.githubusercontent.com/80234931/234469888-17daa77a-8044-4f6e-86a3-e7aedc4387aa.png)

**Comment by Carson-yy** [comment]
> ![image](https://user-images.githubusercontent.com/80234931/234470142-d7f5ca15-74ad-4f78-aabf-631c73076493.png) 工作树如上图，dao层中是mapper文件，mapper文件夹是xml文件。 在dao层里标记了mapper文件，无法在mapper文件夹中自动生成对应的xml文件(没有任何提示)， ![image](https://user-images.githubusercontent.com/80234931/234469973-df41d7a6-741c-4abf-876a-7bf4afc01f8d.png) 但是在mapper文件夹里面自己手动创建好一个完整的xml文件后，在dao里面写方法会在创建的xml里面自动生成对应节点 ![image](https://user-images.githubusercontent.com/80234931/234470013-ec1df6c3-c6e7-4e88-85be-44079ee9679d.png) ![image](https://user-images.githubusercontent.com/80234931/234469888-17daa77a-8044-4f6e-86a3-e7aedc4387aa.png)

目前这项实际上被移除了，在判断当前接口Mapper是否为Mybatis的时候，实际上是有难度的，目前还在考虑如何准确的识别Java文件是一个mybatis Mapper文件（每个企业或者开发者都会以不同方式来编写），所以当前实现逻辑是从xml反向找java，实际上也是因为初始化扫描的时候，java文件过于多的原因，这块在设计中，后续会以更舒适的方式完成，

**Comment by RoureUnder** [comment]
感谢回复，有没有可能采用主动生成的方式，用户选择生成路径，然后再根据mapper的信息自动生成xml文件（当然只是一点拙见），祝开发顺利

**Comment by Carson-yy** [comment]
> 感谢回复，有没有可能采用主动生成的方式，用户选择生成路径，然后再根据mapper的信息自动生成xml文件（当然只是一点拙见），祝开发顺利

这个已经安排到日程上了，初步设计是增加右键创建Mapper xml的功能，届时还有通过SQL以及连接表直接生成等功能
